### ISSUE TITLE
Eurostat: Change "Germany (until 1990 former territory of the FRG)" to "Germany"

### ISSUE THREAD

**Issue by cueneythizli** [policycompass/policycompass#592] opened 2016-06-06 14:02 UTC

**Comment by cbotsikas** [comment] 2016-07-22 12:52
How can i reproduce this issue?

**Comment by YuriGlickman** [comment] 2016-07-22 13:17
It is easy. The general issue is that it is impossible to change the name of the dimension when you are uploading a  data table. You can select a cell of the table to take the text from it as the dimension, but you cannot edit it.  Thus ticket has to fix this bug.
Sometimes data tables from Eurostat contain another name fro Germany. For example if you try to import from Eurostat by searching this dataset: "Causes of death - absolute number - annual data" you will repeat the issue.

**Comment by cbotsikas** [comment] 2016-07-22 13:55
Thank you Yuri, it took me some time to find the proper selections in order to see some data..
Are you referring to the table data like in the following screenshot or the dropdown GEO value?
![image](https://cloud.githubusercontent.com/assets/1640100/17058782/3c0004ba-5022-11e6-922d-8368348ac99a.png)

While you are on the first step, you can edit the values so that the dimensions on step 2 can be correct. Isn't that enough? 
![image](https://cloud.githubusercontent.com/assets/1640100/17059184/490f1306-5024-11e6-8e59-7ec77189bbe8.png)

With the proposed changes, i find it too restrictive to have a hard coded rule where we replace all phrases starting with Germany into "Germany". If someone is familiar with Eurostat's dataset, he might find it confusing that the content imported is altered.

**Comment by YuriGlickman** [comment] 2016-07-22 14:58
I am refering to the cell A2.
I did not know that I can edit the table at the step 1. I always thought about it as a preview. From another side I recognised the for editing only at the second step and it would be better to be able to edit it at the second step...
I am against of any hard coded rules as well.

Som the issue is solved for me.

**Comment by cbotsikas** [comment] 2016-07-24 23:35
I've closed the PR. I'll leave it to @FabiApfelkern if he wants to create a new issue for editing data on the second step and close this issue.

**Closed** 2016-08-31 08:46 UTC
Labels: DATASET MANAGER
