### ISSUE TITLE
Deployment via Make always needs to be executed twice

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#176] opened 2015-08-12 13:41 UTC
Everytime Make is executed for deployment it stops with the following error [1]. If then the Make is just executed again it works. The next execution fails and so on. 

[1] 
```
cd policycompass-services && bin/python3.4 manage.py migrate
Traceback (most recent call last):
  File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
ImportError: No module named 'config.settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'config.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named 'config.settings'
make: *** [services_install] Error 1
```

**Comment by nidico** [comment] 2015-08-12 14:31
Duplicate of #163. The broken links are the cause for the error above.

**Closed by nidico** 2015-08-12 14:31 UTC
Labels: bug, DEPLOYMENT
