### ISSUE TITLE
Save Model Dialogue

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#153] opened 2015-07-16 16:18 UTC
In the Save Model Dialogue change the following:
1) Rename the "FCM Model" dialogue to "Causal Model Attributes"
2) "Policy domains" window should be bigger and font size in it should be smaller
3) After saving I see 2 pop-up windows. The second one is not needed. As I understand you are using it for debugging, but you can deactivate it for the success case.

**Comment by belalakbar** [comment] 2015-07-27 16:05
Model save dialog, we use the <div class="modal-body">, I am unable to find the style for the model-body in the project. Who can tell about this? 
This will affect this thing:
2) "Policy domains" window should be bigger and font size in it should be smaller

**Comment by FabiApfelkern** [comment] 2015-08-03 09:33
Actually Brunel has developed this, so you should know best. :)
But the modal is defined here: https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/fcm/controllers/cytoscape.js
in line 953.

**Comment by belalakbar** [comment] 2015-08-04 10:06
@ Fabian, yes brunel are the main contributor in FCm but for the style, class " model-body", which I am unable to find (probably given by design team)  . Yuri has asked the nadia to help and I have already send miquel the code I am working on and now waiting for his response to my e-mail.

**Comment by mmilaprat** [comment] 2015-08-04 10:13
Last week we send you some emails about it. You didn't receive it?

**Comment by belalakbar** [comment] 2015-08-04 10:18
no, my account is changed as
was that account 

Bilal.chuddher2@brunel.ac.uk

**Comment by mmilaprat** [comment] 2015-08-04 10:25
I'm going to forward the emails

**Comment by belalakbar** [comment] 2015-08-04 10:27
thanks

**Comment by YuriGlickman** [comment] 2015-08-13 12:35
After sucessful sacing of a model I get a pop-up window with message "Message here" and with the title "FCM". Please replase "Message here" by a meanful text like "The causal model has been succesfully saved" and the header "Confirmation".

**Comment by YuriGlickman** [comment] 2015-08-13 12:45
2) "Policy domains" window should be bigger and font size in it should be smaller

**Comment by aquinas9** [comment] 2015-08-14 10:27
(1) pop-message
the message was put there to explain the user that they should save model for there use (At the moment, we don't have "user session" for their own usage). Actually the browsed models are not save according to user id. Therefore for cc meeting after discussion we put this message for ccc trial. 

But after discussion and your suggestion as user we consider to remove this message and will change the pop-up message for saving model. 

(2)"Policy domains" window should be bigger and font size in it should be smaller => As Bilal said in the last telco, this will be done in next sprint.

**Comment by aquinas9** [comment] 2015-08-14 10:29
We will close this issues and we will put (2) of this issue into next sprint as a new issues.

**Closed by aquinas9** 2015-08-14 10:29 UTC
Labels: FCM
