### ISSUE TITLE
Deployment via Make destroys symbolic links

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#175] opened 2015-08-12 13:39 UTC
When you execute Make for deployment at least two symbolic links get destroyed. The catalina.sh in bin and the nginx.conf in etc. The application can not be started then with Supervisor. 

```
lrwxrwxrwx  1 policycompass policycompass      11 Aug 12 15:29 catalina.sh -> catalina.sh
lrwxrwxrwx  1 policycompass policycompass   10 Aug 12 15:34 nginx.conf -> nginx.conf
```

**Comment by nidico** [comment] 2015-08-12 13:41
Duplicate of #163.

**Closed by nidico** 2015-08-12 13:41 UTC
Labels: bug, DEPLOYMENT

**Comment by FabiApfelkern** [comment] 2015-08-12 13:42
Sorry
