### ISSUE TITLE
upload dataset - cannot save and finish

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#319] opened 2015-10-26 14:21 UTC
In the Upload dataset wizard, when I finalise the wizard and click on Save & Finish I get the error message:
title: Dataset with this Title already exists.
acronym: Dataset with this Acronym already exists.

But if I search I cannot find any

when I go back to start again, the date of the wizard is still there
![capture](https://cloud.githubusercontent.com/assets/4747814/10731331/32165820-7bf5-11e5-8185-ae5e431249ad.JPG)

**Comment by FabiApfelkern** [comment] 2015-10-26 14:32
Actually the dataset was saved but not indexed because there is an error in it. Can you send me the table you tried to upload? That the data is still there is a feature to prevent the loss of data because there are so many steps. It is cached in the browser storage. You can use the "Cancel" button to empty it.

**Comment by nadiapo** [comment] 2015-10-27 12:07
I tried to upload another dataset and I get again an error at the end when clicking save & Finish:

![capture](https://cloud.githubusercontent.com/assets/4747814/10757480/973a9be2-7cab-11e5-9cfd-ca223dbb7e75.JPG)

**Comment by FabiApfelkern** [comment] 2015-10-27 12:20
Can you send me a screenshot from Step 6, where you see the final dataset? I bet we have just some misunderstandings how to use the wizard and I forgot to catch some wrong data. Thanks.

**Comment by nadiapo** [comment] 2015-10-27 12:22
![capture](https://cloud.githubusercontent.com/assets/4747814/10757849/c87e2f28-7cad-11e5-850b-e83b8b0a43fb.JPG)

**Comment by FabiApfelkern** [comment] 2015-10-27 12:25
Thanks

**Comment by FabiApfelkern** [comment] 2015-10-27 15:27
@nadiapo Can you please try again, but in Step 2 under "Data Dimension Type" choose "Custom".

**Comment by FabiApfelkern** [comment] 2015-10-28 10:34
@nadiapo I found the real bug. The problem is that the pandas library as problems with dates before the unix timestamp started, so before 1970. I will fix it as soon as possible.

**Comment by FabiApfelkern** [comment] 2015-10-28 12:42
This should be fixed and it is already deplyoed on Stage. Can you test it there please? I also deleted the corrupted datasets on Alpha.

**Comment by nadiapo** [comment] 2015-10-28 13:30
I tried it and it works on stage. Can you delete again corrupted datasets on alpha and let me know when I can proceed with the scenario on alpha?

**Comment by FabiApfelkern** [comment] 2015-10-28 13:39
Great. I will do that today and let you know.

**Comment by FabiApfelkern** [comment] 2015-10-28 14:14
@nadiapo I deployed it to Alpha. Please try it again.

**Closed** 2015-11-02 14:02 UTC
Labels: bug, DATASET MANAGER
