### ISSUE TITLE
Deleting selected dimension items difficult

### ISSUE THREAD

**Issue by rukala** [policycompass/policycompass#350] opened 2015-11-04 10:31 UTC
When I want to delete selected fields of a dataset for a specific data dimension type in the list on the right, and this list is long so it can be scrolled, the scroll bar lies above the delete "x" of the individual items.

![bildschirmfoto 2015-11-04 um 11 30 30](https://cloud.githubusercontent.com/assets/11075214/10935617/833e55d8-82e7-11e5-9d51-a00b6ff4b3c4.png)

**Comment by FabiApfelkern** [comment] 2015-11-04 10:41
@rukala What browser do you use?

**Comment by rukala** [comment] 2015-12-17 10:30
If I remember correctly, this was Firefox. But I think it also happened in Chrome. If you want I can try to reproduce it.

**Comment by FabiApfelkern** [comment] 2015-12-17 10:51
Yes please. I tried FF and Chrome and I cannot reproduce it. I guess it is because you are using MacOS, aren't you?

**Comment by cbotsikas** [comment] 2015-12-17 11:05
I guess it's related to MacOS, judging from the scrollbar style.. In windows, it's working fine.
![image](https://cloud.githubusercontent.com/assets/1640100/11868180/694624c6-a4b6-11e5-8a9d-93720542619f.png)

**Comment by cbotsikas** [comment] 2015-12-17 11:19
I don't have any Mac around to test this out, can you send a screenshot of what you see here: http://jsfiddle.net/t4cf2u31/1/
For me it looks like this:
![image](https://cloud.githubusercontent.com/assets/1640100/11868492/6fb2d816-a4b8-11e5-94f0-069e647ccd80.png)

**Comment by cbotsikas** [comment] 2015-12-17 11:57
I asked @skous to test it out o Max OS X (10.11.2) and worked fine as seen on the screenshot for Firefox, Chrome and Safari.. 
![capture](https://cloud.githubusercontent.com/assets/1640100/11869135/4cda7358-a4bd-11e5-916a-b75a729ee66c.PNG)

@rukala are you using Mac OS an a laptop with just the trackpad? Does it have the same behavior with a mouse connected?

**Comment by cbotsikas** [comment] 2015-12-17 14:25
Upon further investigation, this issue is related with how Mac browsers handle pages when using trackpad and there is none physical mouse exists (if you plug a mouse to your laptop, instantly the scrollbars are fixed and behave like normal). Apparently this is not a Policy Compass bug but a Mac feature, thus i think it's safe to close this issue.

The scrollbar is only shown when the user scrolls on top of the list. If you hover over the scrollbar, it makes the effect seen in the first post. If you move the cursor away it will disappear, and you can use the delete buttons without issues. 

@rukala can you please confirm this?

**Closed** 2015-12-17 16:27 UTC
Labels: DATASET MANAGER, DESIGN

**Comment by rukala** [comment] 2016-01-05 14:57
@cbotsikas @FabiApfelkern Sorry for my late reply - somehow my GitHub notifications are not working - I can reproduce this when using mac ox 10.11.2 with touchpad/bluetooth mouse.

So yes the scroll bar appears when you move the mouse over it or scroll - and this is the problem since this blocks me from deleting/pressing the "x" button underneath. Since this is a very detailed usability issue I think we can leave it for now. Thanks for looking into it!
